export const IconName = {
  FACEBOOK: 'facebook',
  INSTAGRAM: 'instagram',
  YOUTUBE: 'youtube',
  TWITTER: 'twitter',
  LINKEDIN: 'linkedin',
  EMAIL: 'email',
  INTERNAL: 'internal',
  EXTERNAL: 'external',
  MEDIA: 'media',
  FILE: 'file',
  DEFAULT: 'default',
  ARROW_RIGHT: 'arrow-right',
  ARROW_LEFT: 'arrow-left',
  PLAY: 'play',
  LINE_PLAY: 'line-play',
  ARROW_UP_RIGHT: 'arrow-up-right',
  DIVERSITY: 'diversity',
  COMMUNITIES: 'communities',
  CROSS_ARROWS: 'cross-arrows',
  SIGNAL: 'signal',
} as const;
