---
ID: "fa9fe1ac-ad02-4e11-83ac-a5172aab5257"
Parent: "b0602368-f67c-433c-8700-862d480546d0"
Template: "b0602368-f67c-433c-8700-862d480546d0"
Path: "/sitecore/templates/Project/click-click-launch/Site/Article Page/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 2
    Fields:
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{EE5191AB-D41F-4FD4-A46D-3DB95BA6EBA2}"
              p:before="*"
              s:ds="local:/Data/Article Header"
              s:id="{DD6C6E80-1458-4276-B753-001691C8841C}"
              s:par="GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;FieldNames&amp;Styles&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=3"
              s:ph="/headless-main/container-fullbleed-2" />
            <r
              uid="{D61AB6FE-6379-4953-B42A-797F650313EE}"
              p:after="r[@uid='{EE5191AB-D41F-4FD4-A46D-3DB95BA6EBA2}']"
              s:ds="local:/Data/Text 1"
              s:id="{50B36874-8C4E-4958-9DD6-8B95C6AFD09A}"
              s:par="CSSStyles&amp;DynamicPlaceholderId=5"
              s:ph="/headless-main/container-seventy-4" />
            <r
              uid="{1E24F50F-ECAD-4925-B028-654B93A1652E}"
              p:after="r[@uid='{D61AB6FE-6379-4953-B42A-797F650313EE}']"
              s:id="{E80C2A78-FCC2-4D32-8EC5-4133F608BE5C}"
              s:par="backgroundColor&amp;excludeTopMargin=1&amp;inset&amp;CSSStyles&amp;DynamicPlaceholderId=2"
              s:ph="headless-main" />
            <r
              uid="{75B94739-C82C-4BEC-978D-C2811C31B09A}"
              p:after="r[@uid='{1E24F50F-ECAD-4925-B028-654B93A1652E}']"
              s:id="{3F9CCCB1-7BD7-4245-A3E9-91ED43575D98}"
              s:par="excludeTopMargin&amp;CSSStyles&amp;DynamicPlaceholderId=4&amp;Styles=%7B417CFF95-A3B6-4A1D-B10A-D41D449CE5FA%7D%7C%7BAE80F34C-96EF-4B45-8028-78EE7FB5B559%7D%7C%7BEF966498-A54E-44F1-80B4-917F0535B239%7D"
              s:ph="headless-main" />
            <r
              uid="{4C752E16-9289-437C-ADC2-B88FBCC652C4}"
              p:after="*[1=2]"
              s:ds="df7e1cbb-0b9d-4aa8-b66e-3a93539711b5"
              s:id="{D806DDF7-39A7-4A6D-8E0A-D138BC53845D}"
              s:par=""
              s:ph="headless-main" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240304T202210Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "29c783d7-ba29-435c-949d-f8c0ee43487e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260511T185255Z
    - ID: "efbce7e8-6d4e-49e2-9b48-a9ab9a1e6fd7"
      Hint: pageThumbnail
      Value: 
